[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.26'
evm_version = 'cancun'
optimizer = true
optimizer_runs = 1_000_000
ffi = true
fs_permissions = [{ access = "read", path = "./" }]

[fmt]
line_length = 120
tab_width = 4
